os:
    - linux
    - osx

matrix:
    include:
        - python: "3.6"
          env: EXTRAPKGS=
        - python: "3.7"
          env: EXTRAPKGS=
        - python: "3.8"
          env: EXTRAPKGS=

        - python: "3.6"
          env: EXTRAPKGS=psutil
        - python: "3.7"
          env: EXTRAPKGS=psutil
        - python: "3.8"
          env: EXTRAPKGS=psutil

install:
    - pip install setuptools_scm pytest pytest-cov $EXTRAPKGS

script:
    - pytest --cov=taskgraph --cov-report=term
