pipelines:
  default:
    - step:
        name: Test on python2.7
        image: python:2.7-stretch
        caches:
          - pip
        script:
          - tox -e py27
    - step:
        name: Test on python3.6
        image: python:3.6-stretch
        caches:
          - pip
        script:
          - tox -e py36
